apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ $.Release.Name }}
spec:
  rules:
  - host: {{ required "appHost is required" $.Values.appHost }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}
          servicePort: 80
        path: /
  - host: {{ printf "%s.%s" "www" $.Values.appHost }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}
          servicePort: 80
        path: /
  tls:
    - hosts:
        - {{ $.Values.appHost }}
        secretName: {{ printf "%s-%s" $.Release.Name "bookstack" }}